Refacting the vala doc
colinkiama/vala-docs pull request #50
Opened 2024-10-02 13:51 UTC by nda-cunh

add missing documentation and exemple

2024-10-09 08:42 UTC, lw64 commented on source/tutorials/programming-language/main/01-00-first-program.rst
> +   stdout.printf("Hello, World\n");
for beginners I think just `print()` is better. Then there can be a note explaining that in actual projects people prefer `stdout.printf()` and why, maybe in the section also where the different main() variants are explained

2024-10-11 11:11 UTC, colinkiama commented
You've done amazing work however, the title suggests that there's only refactoring going on. I see that some brand new content is being added too.

Once you've pushed all the changes here that you want to do, can you split this merge request into multiple smaller merge requests please?

This way, we can get the content reviewed and merged in much faster! ;)

2024-10-15 13:58 UTC, nda-cunh commented on source/tutorials/programming-language/main/01-00-first-program.rst
> +   stdout.printf("Hello, World\n");
It's fine with me, I agree, to show the world that à la is easy to write! 😎

2024-10-15 14:01 UTC, nda-cunh commented
> Vous avez fait un travail incroyable, mais le titre suggère qu'il ne s'agit que d'une refactorisation. Je vois que du nouveau contenu est également ajouté.
> 
> Une fois que vous avez appliqué toutes les modifications que vous souhaitez effectuer ici, pouvez-vous diviser cette demande de fusion en plusieurs demandes de fusion plus petites, s'il vous plaît ?
> 
> De cette façon, nous pouvons examiner et fusionner le contenu beaucoup plus rapidement ! ;)



> You've done amazing work however, the title suggests that there's only refactoring going on. I see that some brand new content is being added too.
> 
> Once you've pushed all the changes here that you want to do, can you split this merge request into multiple smaller merge requests please?
> 
> This way, we can get the content reviewed and merged in much faster! ;)

I'm terrible at choosing names for MR titles!  I haven't finished yet, so I'm going to add some pages on partial class. can you help me find another title?

2024-10-15 14:06 UTC, nda-cunh commented
> You've done amazing work however, the title suggests that there's only refactoring going on. I see that some brand new content is being added too.
> 
> Once you've pushed all the changes here that you want to do, can you split this merge request into multiple smaller merge requests please?
> 
> This way, we can get the content reviewed and merged in much faster! ;)

I'm terrible at choosing names for MR titles!  I haven't finished yet, so I'm going to add some pages on partial class
can you help me find another name?

2024-10-19 17:29 UTC, colinkiama commented
Your commit titles can be used as the pull request titles.

2025-01-10 06:33 UTC, lw64 commented
Hey, still working on it? :D

2025-04-07 02:22 UTC, nda-cunh commented
> Hey, still working on it? :D

No but soon

2026-04-18 21:42 UTC, colinkiama commented
@nda-cunh Don't worry about the pull request titles anymore. I'm just going to review what you've done so far.

However, please do your work on partial classes on a separate PR. Name it something like "Partial Classes Improvements"

2026-04-18 22:34 UTC, colinkiama requested changes
Here are some changes to make.

There are some grammar changes too but they can be done at the end. Very small.

Focus on these changes for now.

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/02-00-basics/02-07-language-elements.md
> +        return Math.sqrt((x - other.x) * (x - other.x) + (y - other.y) * (y - other.y));
Coding style should to match rest of docs

```suggestion
        return Math.sqrt ((x - other.x) * (x - other.x) + (y - other.y) * (y - other.y));
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/02-00-basics/02-07-language-elements.md
> +}
Coding style should match rest of docs.
```suggestion
void main () {
    print (EnumName.VALUE1.to_string ());  // prints "Value 1"
    print (EnumName.VALUE2.to_string ());  // prints "Value 2"
    print (EnumName.VALUE3.to_string ());  // prints "Value 3"
}
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/02-00-basics/02-07-language-elements.md
> +}
Coding style should match rest of docs:

```suggestion
void main () {
    MyFlags flags;

    flags = MyFlags.FLAG1 + MyFlags.FLAG3;

    if (MyFlags.FLAG1 in flags)
        print ("FLAG1 is set");
    if (MyFlags.FLAG2 in flags)
        print ("FLAG2 is set");
    if (MyFlags.FLAG3 in flags)
        print ("FLAG3 is set");
}
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/02-00-basics/02-09-input-output.md
> +You already know *stdout.printf()* from the *Hello World* example.  Actually, it can take an arbitrary number of arguments of different types, whereas the first argument is a *format string*, followi
Should consistently have space before a pair of parenthesis when calling a method:

```suggestion
You already know `stdout.printf ()` from the *Hello World* example.  Actually, it can take an arbitrary number of arguments of different types, whereas the first argument is a *format string*, following the same rules as [C format strings](http://en.wikipedia.org/wiki/Printf). If you must output an error message you can use `stderr.printf ()` instead of `stdout.printf ()`.
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/02-00-basics/02-09-input-output.md
> +stdout.printf("%d %g %s\n", 42, 3.1415, "Vala");
```suggestion
stdout.printf ("Hello, world\n");
print ("Hello, world\n");
stdout.printf ("%d %g %s\n", 42, 3.1415, "Vala");
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/02-00-basics/02-09-input-output.md
> +printerr("I'm an error message !");
```suggestion
stderr.printf ("I'm an error message !");
printerr ("I'm an error message !");
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/02-00-basics/02-09-input-output.md
> +for debugging message vala provides `debug()`, `message()`, `warning()` and `critical()` functions.
```suggestion
for debugging message vala provides `debug ()`, `message ()`, `warning ()` and `critical ()` functions. 
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/02-00-basics/02-09-input-output.md
> +critical("I'm a critical message !");
```suggestion
message ("I'm a message !");
warning ("I'm a warning !");
critical ("I'm a critical message !");
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/02-00-basics/02-09-input-output.md
> +}
```suggestion
string? line;
while ((line = stdin.read_line ()) != null) {
    stdout.printf ("You entered: %s\n", line);
}
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/02-00-basics/02-09-input-output.md
> +Or use *stdin.scanf()* function to read formatted input from the console.
```suggestion
Or use `stdin.scanf ()` function to read formatted input from the console.
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/02-00-basics/02-09-input-output.md
> +stdout.printf("You were born on %d/%d/%d\n", day, month, year);
```suggestion
int day, month, year;
stdout.printf ("Enter your birthday (dd/mm/yyyy): ");
stdin.scanf ("%d/%d/%d", out day, out month, out year);
stdout.printf ("You were born on %d/%d/%d\n", day, month, year);
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/02-00-basics/02-09-input-output.md
> +if you want `stdin.scanf()` with %s format, you must create a buffer to store the input.
```suggestion
if you want `stdin.scanf ()` with %s format, you must create a buffer to store the input.
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/02-00-basics/02-09-input-output.md
> +stdout.printf("You entered: %s\n", (string)buffer);
```suggestion
stdin.scanf ("%s", out buffer);
stdout.printf ("You entered: %s\n", (string)buffer);
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/02-00-basics/02-09-input-output.md
> +```
```suggestion
To open a file, you can use the `FileStream.open ()` function. This function takes the name of the file and the mode in which you want to open the file. The mode can be one of the following:

```vala
var fs = FileStream.open ("toto.txt", "r");
if (fs == null) {
    print ("Cannot open file");
    return ;
}

string ?line = null;
while ((line = fs.read_line ()) != null) {
    print (line);
}
```
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/02-00-basics/02-09-input-output.md
> +```
```suggestion
You can use `FileUtils.get_contents ()` and `FileUtils.set_contents ()` functions to read and write the content of a file.

```vala
string content;
FileUtils.get_contents ("my_text.txt", out content);
// get all content of the file

string new_content = content.replace ("a", "b");
// replace all 'a' by 'b' and set the new content to the file
FileUtils.set_contents ("my_text.txt", new_content);
```
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/04-00-advanced-features/04-07-the-main-loop.md
> +```
```suggestion
```vala
async void main () {
    Timeout.add (2000, () => {
        stdout.printf ("Time!\n");
        Idle.add (main.callback);
        return false;
    });

    yield;
}
```
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/04-00-advanced-features/04-08-asynchronous-methods.md
> +the supra_calculator function execute a blocking thread just after it will use the `yield` keyword which makes us return to the main and it can continue to print the 'Hi !' every second. once the Thr
```suggestion
the supra_calculator function execute a blocking thread just after it will use the `yield` keyword which makes us return to the main and it can continue to print the 'Hi !' every second. once the Thread has finished executing it uses `Idle.add (supra_calculator.callback);` which indicates that the program can return to the function at the time of the yield. we join the thread and retrieve the calculation and we return it to retrieve it in the main
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/04-00-advanced-features/04-08-asynchronous-methods.md
> +```
```suggestion
```vala
async int supra_calculator (int ms) {
    var thread = new Thread<int> (null, () => {
        int n = 0;
        // make a hard calculation:
        n = 12 * ms;
        Thread.usleep (ms * 1000);
        Idle.add (supra_calculator.callback);
        return n;
    });
    yield;

    var result = thread.join ();
    return result;
}

async void main() {

    // Every second, print "Hi !"
    Timeout.add (1000, () => {
        print (@"Hi !\n");
        return true;
    });

    int res = yield supra_calculator (4000);
    print (@"result: $res\n");
}
```
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/04-00-advanced-features/04-08-asynchronous-methods.md
> +the output:
Could render the output in a code block with an `output` syntax language or just a standard code block.

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/01-00-first-program.md
> +stdout.printf("Hello, World\n");
```suggestion
stdout.printf ("Hello, World\n");
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/01-00-first-program.md
> +---
I think that a heading should be introduced here instead so that the new section can actually be named and referenced

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/01-00-first-program.md
> +        public static void main(string[] args) {
```suggestion
        public static void main (string[] args) {
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/01-00-first-program.md
> +    stdout.printf("Hello, World\n");
```suggestion
    stdout.printf ("Hello, World\n");
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/02-00-basics/02-07-language-elements.md
> +## 2.7.3. Anonymous Methods / Closures (lambda expressions)
```suggestion
## 2.7.3. Anonymous Methods / Closures (Lambda Expressions)
```

2026-04-18 22:34 UTC, colinkiama commented on docs/tutorials/programming-language/main/02-00-basics.md
> +      <li><a href="02-00-basics/02-07-language-elements#_2-7-3-anonymous-methods-closures-lambda-expressions">2.7.3. Anonymous Methods / Closures (lambda expressions)</a></li>
```suggestion
      <li><a href="02-00-basics/02-07-language-elements#_2-7-3-anonymous-methods-closures">2.7.3. Anonymous Methods / Closures (Lambda Expressions)</a></li>
```

2026-05-09 23:15 UTC, colinkiama approved these changes

2026-05-09 23:15 UTC, merged